/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0D5C3A",
        "primary-dark": "#073B24",
        "primary-light": "#10B981",
        "on-primary": "#ffffff",
        "primary-container": "#E8F5EE",
        "on-primary-container": "#064E2E",
        "accent-gold": "#D4AF37",
        "accent-gold-light": "#FDF0CD",
        "accent-gold-dark": "#99730E",
        "accent-rose": "#E11D48",
        "accent-rose-light": "#FFE4E6",
        "secondary": "#5C6B61",
        "on-secondary": "#ffffff",
        "secondary-container": "#F0F4F1",
        "on-secondary-container": "#243329",
        "tertiary": "#C89334",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#FEF7E6",
        "on-tertiary-container": "#784B06",
        "background": "#FAF8F5",
        "on-background": "#18221B",
        "surface": "#ffffff",
        "on-surface": "#18221B",
        "surface-variant": "#F0EBE1",
        "on-surface-variant": "#4E5C52",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#FAF8F5",
        "surface-container": "#F3EFE7",
        "surface-container-high": "#ECE6DC",
        "surface-container-highest": "#DFD7CA",
        "outline": "#9EAAA1",
        "outline-variant": "#E0D8CB",
        "error": "#E11D48",
        "error-container": "#FEE2E2",
      },
      fontFamily: {
        serif: ["'Playfair Display'", "Georgia", "serif"],
        sans: ["'Plus Jakarta Sans'", "'Inter'", "sans-serif"],
        arabic: ["'Amiri'", "serif"],
        display: ["'Outfit'", "'Plus Jakarta Sans'", "sans-serif"],
      },
      spacing: {
        "max-width": "480px",
        "container-padding": "24px",
        "section-gap": "36px",
        "stack-gap": "16px",
      },
      boxShadow: {
        "ambient": "0 12px 36px rgba(13, 92, 58, 0.12)",
        "card": "0 10px 30px rgba(24, 34, 27, 0.06)",
        "gold": "0 10px 25px rgba(212, 175, 55, 0.25)",
        "emerald": "0 10px 25px rgba(13, 92, 58, 0.25)",
        "glow": "0 0 25px rgba(13, 92, 58, 0.35)",
      }
    },
  },
  plugins: [],
}

